import type { NextPage } from 'next';
import { useState } from 'react';
import Head from 'next/head';
import { css } from '@emotion/react';
import { register } from 'styles';
import { TitleBar, Input } from 'components';
import { Formik, Form, Field } from 'formik';
import { EmailPhone } from 'sections';

interface SignUpFormValues {
  email: string;
  phone: string;
  verificationCode: string;
  fullName: string;
  accountID: string;
  password: string;
  confirmPassword: string;
  seedPhrase: string[];
}

const Home: NextPage = () => {
  const [step, setStep] = useState('');
  const initialValues: SignUpFormValues = {
    email: '',
    phone: '',
    verificationCode: '',
    fullName: '',
    accountID: '',
    password: '',
    confirmPassword: '',
    seedPhrase: [''],
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        css={css`
          ${register}
        `}
      >
        <TitleBar />
        <Formik
          initialValues={initialValues}
          onSubmit={(values, actions) => {
            console.log({ values, actions });
            actions.setSubmitting(false);
          }}
        >
          <Form>
            {/* Phone Section */}
            <EmailPhone />
            {/* Phone Section End */}
          </Form>
        </Formik>
      </div>
    </div>
  );
};

export default Home;
